config/routes.rb
Rails.application.routes.draw do

  get "/home", to: "static_pages#home"
  get  "/help", to: "static_pages#help"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  root "static_pages#home"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-abeli navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
        <%= image_tag "icon.png", size: "80", class: "navbar-brand" %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Blogs</a></li>
        <li><a href="#">Menu</a></li>
        <li><a href="#">Tips</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
        <% else %>
          <li><%= link_to "Signup", signup_path, class: "fa fa-user" %></a></li>
          <li><%= link_to "Login", login_path, class: "fa fa-sign-in" %></a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | All for the health of your family</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/nav" %>
    <div class="container main">
      <%= render "layouts/flash" %>
      <div class="row">
        <% if logged_in? %>
          <div class="col-sm-9">
            <%= yield %>
          </div>
          <div class="col-sm-3">
            <div class="sidebar-nav-fixed pull-right affix">
              <div class="well">
                <div class="well">
                  <p>Upcoming Events:</p>
                </div>
                <div class="well">
                  <p>Tracking</p>
                </div>
                <div class="well">
                  <p>Index</p>
                </div>
                <div class="well">
                  <p>Friends</p>
                </div>
              </div>
          </div>
        </div>
      <% else %>
        <div class="col-sm-12">
            <%= yield %>
          </div>
      <% end %>
    </div>
  </div>
  </body>
</html>